name: movie_app
description: "A 3-screen TMDB Movie Application in Flutter with offline watchlist and theme switching."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1

  # State Management
  provider: ^6.1.2

  # Networking & HTTP Client
  dio: ^5.7.0

  # Declarative Navigation
  go_router: ^14.8.0

  # Offline Persistence (Watchlist & Preferences)
  shared_preferences: ^2.3.5

  # Connectivity
  connectivity_plus: ^6.1.0

  # Utilities & Formatting
  intl: ^0.20.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/

